load_pickle:
  # SimulationHistory: "SimulationHistory.pickle"
  NeuralStrategy: "NeuralStrategy.pickle"

PygameInterface:
  screen_width: 1000
  screen_height: 800
  border_x: 5
  border_y: 5
  border_between_cells: 5

Board:
  size_x: 10
  size_y: 10
  num_of_items: 20
  max_health: 10
  level_map_path: "level_maps/level10x10.txt"
  player_names:
  - cock
  - shmara
  - david
  - guzeeva
